[phases.setup]
nixPkgs = ["php82", "php82Packages.composer"]

[phases.install]
cmds = ["composer install --optimize-autoloader --no-dev", "npm ci", "npm run build"]

[phases.build]
cmds = [
  "mkdir -p storage/framework/{sessions,views,cache}",
  "mkdir -p storage/logs",
  "mkdir -p bootstrap/cache",
  "mkdir -p database",
  "touch database/database.sqlite",
  "chmod -R 775 storage bootstrap/cache database"
]

[start]
cmd = "bash start.sh"
